package com.epul.ergosum.metier;


// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/**
 * Catalogue generated by hbm2java
 */
public class Catalogue implements java.io.Serializable {

	private int annee;
	private int quantiteDistribuee;
	private HashMap<Categorie, Integer> statcategorie;

	public Catalogue() {
	}

	public Catalogue(int annee, int quantiteDistribuee) {
		this.annee = annee;
		this.quantiteDistribuee = quantiteDistribuee;
	}


	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	public int getQuantiteDistribuee() {
		return this.quantiteDistribuee;
	}

	public void setQuantiteDistribuee(int quantiteDistribuee) {
		this.quantiteDistribuee = quantiteDistribuee;
	}

	public HashMap<Categorie, Integer> Statcategorie() {
		return statcategorie;
	}

	public void setStatcategorie(HashMap<Categorie, Integer> statcategorie) {
		this.statcategorie = statcategorie;
	}

}
