package com.epul.ergosum.metier;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Jouet generated by hbm2java
 */
public class Jouet implements java.io.Serializable {

	private String numero;
	private Categorie categorie;
	private Trancheage trancheage;
	private String libelle;

	public Jouet() {
	}

	public Jouet(String numero, Categorie categorie, Trancheage trancheage) {
		this.numero = numero;
		this.categorie = categorie;
		this.trancheage = trancheage;
	}

    public Jouet(String numero, Categorie categorie, Trancheage trancheage, String libelle) {
        this.numero = numero;
        this.categorie = categorie;
        this.trancheage = trancheage;
        this.libelle = libelle;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public Categorie getCategorie() {
        return categorie;
    }

    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

    public Trancheage getTrancheage() {
        return trancheage;
    }

    public void setTrancheage(Trancheage trancheage) {
        this.trancheage = trancheage;
    }

    public String getLibelle() {
        return libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
}
